name: Deploy Infra + API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Infrastructure
      - name: Deploy Bicep
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group create \
              --resource-group rg-csvc-core-dev-sea-001 \
              --template-file infra/main.bicep \
              --parameters storageAccountName=stcsvcdevrohitbicep

      # Deploy FastAPI app to Web App
      - name: Deploy FastAPI App
        uses: azure/webapps-deploy@v2
        with:
          app-name: api-csvc-dev-sea-001
          package: ./app
